server:
  port: 8071

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/expensemanager
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
